INSERT INTO Ticket (title, description, status, priority, createdAt, updatedAt) VALUES
('Unable to Connect to VPN', 'User reports being unable to connect to the corporate VPN. Error message indicates authentication failure.', 'OPEN', 'HIGH', NOW(), NOW()),
('Printer Not Responding', 'Network printer in the main office is not responding. Tried restarting the printer and the computer but no luck.', 'OPEN', 'MEDIUM', NOW(), NOW()),
('Email Not Syncing', 'User’s email account is not syncing on their mobile device. They have tried reinstalling the email app without success.', 'STARTED', 'LOW', NOW(), NOW()),
('Software Installation Request', 'Request to install Adobe Creative Cloud on the new employee’s laptop. User needs access as soon as possible.', 'OPEN', 'HIGH', NOW(), NOW()),
('Password Reset', 'User has forgotten their password and is unable to log in. Needs immediate assistance to reset it.', 'CLOSED', 'MEDIUM', NOW(), NOW()),
('Slow Network Performance', 'User reports that the network has been extremely slow throughout the day, affecting productivity.', 'STARTED', 'MEDIUM', NOW(), NOW()),
('Hardware Malfunction', 'The hard drive on the workstation is making unusual noises. User is concerned about potential data loss.', 'OPEN', 'HIGH', NOW(), NOW()),
('Access to Shared Drive', 'User cannot access the shared drive. They receive a permissions error when trying to open it.', 'CLOSED', 'MEDIUM', NOW(), NOW()),
('Update Required for Security Software', 'The security software on several workstations is outdated. Needs updating to the latest version.', 'OPEN', 'LOW', NOW(), NOW()),
('New Employee Setup', 'Request for setting up a new employee with email, access to applications, and hardware installation.', 'OPEN', 'HIGH', NOW(), NOW()),
('Software Update Failure', 'User reports that a recent software update failed and now the application won’t start.', 'STARTED', 'MEDIUM', NOW(), NOW()),
('Network Drive Disconnected', 'User finds that their network drive has been disconnected and cannot access important files.', 'OPEN', 'HIGH', NOW(), NOW()),
('Wi-Fi Connectivity Issues', 'User reports intermittent Wi-Fi connectivity issues, drops in connection frequently.', 'STARTED', 'MEDIUM', NOW(), NOW()),
('Outdated Antivirus Definitions', 'Antivirus software on several systems needs to be updated to the latest definitions.', 'OPEN', 'LOW', NOW(), NOW()),
('New Hardware Request', 'Request for a new monitor for an existing workstation due to screen issues.', 'OPEN', 'MEDIUM', NOW(), NOW()),
('File Recovery Needed', 'User accidentally deleted important files and needs assistance in recovery.', 'STARTED', 'HIGH', NOW(), NOW()),
('Browser Compatibility Issue', 'User is experiencing issues accessing a specific website on Chrome; works fine on Firefox.', 'CLOSED', 'MEDIUM', NOW(), NOW()),
('Cloud Storage Access Issue', 'User cannot access their cloud storage account; needs help resetting credentials.', 'OPEN', 'HIGH', NOW(), NOW()),
('PowerPoint Presentation Issue', 'User is having trouble with PowerPoint crashing during presentations; needs troubleshooting.', 'STARTED', 'MEDIUM', NOW(), NOW()),
('Security Breach Alert', 'Received an alert about a potential security breach. Immediate investigation needed.', 'OPEN', 'HIGH', NOW(), NOW()),
('Email Filter Not Working', 'User’s email filters are not functioning properly, causing important emails to be missed.', 'STARTED', 'LOW', NOW(), NOW()),
('Data Backup Failure', 'Automated data backup failed last night; user needs verification and resolution.', 'OPEN', 'HIGH', NOW(), NOW()),
('Accessing Remote Desktop', 'User is unable to access their remote desktop session; needs assistance.', 'CLOSED', 'MEDIUM', NOW(), NOW()),
('Graphics Software Bug', 'User reports a bug in the graphics software that causes it to crash when exporting files.', 'OPEN', 'HIGH', NOW(), NOW()),
('Keyboard Malfunction', 'User’s keyboard is unresponsive; requests a replacement.', 'OPEN', 'MEDIUM', NOW(), NOW()),
('Cellular Data Connection Issues', 'User is experiencing issues with cellular data on their mobile device.', 'STARTED', 'LOW', NOW(), NOW()),
('Server Down Alert', 'Received an alert that one of the servers is down; needs immediate attention.', 'OPEN', 'HIGH', NOW(), NOW()),
('Intranet Page Not Loading', 'User reports that the intranet page is not loading on their browser.', 'CLOSED', 'MEDIUM', NOW(), NOW()),
('Laptop Battery Replacement', 'User’s laptop battery is not holding a charge and needs to be replaced.', 'OPEN', 'MEDIUM', NOW(), NOW()),
('Third-Party Application Issues', 'User is facing issues with a third-party application crashing on startup.', 'STARTED', 'HIGH', NOW(), NOW()),
('Lost Company Phone', 'User has lost their company-issued phone and needs to report it.', 'OPEN', 'MEDIUM', NOW(), NOW()),
('Webcam Not Working', 'User’s webcam is not functioning properly during video calls.', 'CLOSED', 'LOW', NOW(), NOW()),
('Update Windows OS', 'User requests assistance to update their Windows operating system to the latest version.', 'OPEN', 'MEDIUM', NOW(), NOW()),
('Unresponsive Chat Application', 'User’s chat application is unresponsive; needs troubleshooting.', 'OPEN', 'HIGH', NOW(), NOW()),
('External Hard Drive Access', 'User cannot access the external hard drive; asks for assistance.', 'STARTED', 'MEDIUM', NOW(), NOW()),
('Remote Access Setup', 'Request for remote access setup for a new employee.', 'OPEN', 'HIGH', NOW(), NOW()),
('Issue with Task Management Tool', 'User reports issues with the task management tool not saving changes.', 'CLOSED', 'MEDIUM', NOW(), NOW()),
('Outlook Calendar Sync Issues', 'User is facing issues with Outlook calendar not syncing across devices.', 'STARTED', 'LOW', NOW(), NOW()),
('New Software Purchase Request', 'Request to purchase new project management software for the team.', 'OPEN', 'MEDIUM', NOW(), NOW()),
('Help with Data Analysis Tool', 'User needs help with using a new data analysis tool; requests training.', 'OPEN', 'LOW', NOW(), NOW()),
('Password Expiration Notification', 'User received a password expiration notification but is unable to change it.', 'CLOSED', 'MEDIUM', NOW(), NOW()),
('File Permission Issues', 'User cannot edit shared documents due to permission issues; needs assistance.', 'OPEN', 'HIGH', NOW(), NOW()),
('Antivirus Installation Request', 'Request to install antivirus software on a newly acquired workstation.', 'OPEN', 'MEDIUM', NOW(), NOW());
