import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import MainNav from "@/components/MainNav";
import { ThemeProvider } from "@/components/theme-provider";
import Footer from "@/components/Footer";


const lato = localFont({
  src: [
    {
      path: "./fonts/Lato-Thin.ttf",
      weight: "100",
      style: "normal"
    },
    {
      path: "./fonts/Lato-Light.ttf",
      weight: "300",
      style: "normal"
    },
    {
      path: "./fonts/Lato-Regular.ttf",
      weight: "400",
      style: "normal"
    },
    {
      path: "./fonts/Lato-Bold.ttf",
      weight: "700",
      style: "normal"
    },
    {
      path: "./fonts/Lato-Black.ttf",
      weight: "900",
      style: "normal"
    },
  ],
  variable: "--font-lato",

});


export const metadata: Metadata = {
  title: "Ticket Application",
  description: "Generated by WebWave Inovations",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange>
          <nav className="flex flex-col items-center border-b mb-5 px-5 py-3">
            <div className="max-w-6xl w-full">
              <MainNav />
            </div>
          </nav>
          <main className="flex flex-col items-center">
            <div className="max-w-6xl w-full">
              {children}
            </div>
          </main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
